### ISSUE TITLE
Crash prevention + error logging

### ISSUE THREAD

**Issue by ackagel** [angelolab/AMP#19]
Any form of error seems to not only crash AMP, but doesn't leave a good log of the error that occurred.  Some diligent 'try/except' wrapping can help with this, along with making a dedicated error logging system (pop up w/ error, save `.log` file, etc).

**Comment by ngreenwald** [comment]
This one too before sending it out

**Comment by ackagel** [comment]
Error logging is working.  Crash prevention is a bit trickier, but I think everything's satisfactory now.
