### ISSUE TITLE
centralize point loading/handling?

### ISSUE THREAD

**Issue by ackagel** [angelolab/AMP#21]
'Cohort loading' is only used for viewing tifs, which is nice, but could definitely be used for centralized point loading. 

This would shift the burden of point management onto the main viewer, which has its pros/cons:

Pros:
 - each plugin doesn't need to independently handle points (big pro)
 - point abstraction is consistent
 - cohort loading doesn't feel as gimmicky

Con:
 - peripheral point-related data (label data, cell tables, etc) should be handled by the main viewer (not necessary but looks clunky otherwise imo)

Going to go ahead and say this should happen, but I'm open to reversing course on this

**Comment by ngreenwald** [comment]
I think the cons are less relevant for pre-segmentation analysis steps like bg subtraction/denoising, and the pros seem very pro.
