### ISSUE TITLE
ui testing

### ISSUE THREAD

**Issue by ackagel** [angelolab/AMP#6]
There are allegedly ways to test ui elements (programatic clicking, dragging, etc) in pyqt.  Investigating and implementing this tooling/testing would be extremely beneficial, with regards to less error prone ui and faster dev-time.

**Comment by ngreenwald** [comment]
And also looking into how to test the other general functionality, like logic for window/figure creation, etc. I have to admit I have no idea

**Comment by ackagel** [comment]
I was looking into it a while ago, when I was looking at how to set it up w/ travis.  Apparently `pytest-qt` comes with a `qtbot` object which can simulate user interaction and capture qt related warnings/errors.  I imagine testing for window/figure creation can be done using that as well, but it will probably require some deep documentation diving on my part

**Comment by ngreenwald** [comment]
For sure. Not a top priority in that case. Testing the plugins I imagine
will be much easier
